PREFIX FoR: <http://experts.ucdavis.edu/concept/FoR/>
PREFIX aeq: <http://experts.ucdavis.edu/queries/schema#>
PREFIX afn: <http://jena.apache.org/ARQ/function#>
PREFIX authorship: <http://experts.ucdavis.edu/authorship/>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX experts: <http://experts.ucdavis.edu/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX free: <http://experts.ucdavis.edu/concept/free>
PREFIX harvest_iam: <http://iam.ucdavis.edu/>
PREFIX harvest_oap: <http://oapolicy.universityofcalifornia.edu/>
PREFIX iam: <http://iam.ucdavis.edu/schema#>
PREFIX oap: <http://oapolicy.universityofcalifornia.edu/vocab#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX person: <http://experts.ucdavis.edu/person/>
PREFIX private: <http://experts.ucdavis.edu/private/>
PREFIX purl: <http://purl.org/ontology/bibo/>
PREFIX q: <http://experts.ucdavis.edu/queries/>
PREFIX query: <http://experts.ucdavis.edu/schema/queries/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ucdrp: <http://experts.ucdavis.edu/schema#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX work: <http://experts.ucdavis.edu/work/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
describe ?s where {
 ?s a ?type.
 filter(regex(str(?s),concat("^",str(?uri),"(#|$)")))
} limit ?limit
